const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const source=process.argv[2]||require('path').resolve(__dirname,'../public/index.html');
const dom=new JSDOM(fs.readFileSync(source,'utf8'),{url:'https://test.local/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.ResizeObserver=class{observe(){} disconnect(){}};w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollBy=function(){};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.confirm=()=>true;w.alert=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>null;w.Blob.prototype.text=function(){return new Promise(resolve=>{const r=new w.FileReader();r.onload=()=>resolve(r.result);r.readAsText(this);});};}});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await wait(1800);const w=dom.window,d=w.document;console.log('INITIAL ERRORS',errors);for(const id of ['cloud','knowledge','overview','clients','pipeline','biens','litiges','courtiers','agents','notaires','ambassadeurs']){try{w.SigmaCRM.openView(id);console.log('VIEW',id,!d.getElementById(id+'View').classList.contains('hidden'))}catch(e){errors.push(id+': '+e.stack)}}
const id=w.SigmaCRM.createLead({firstName:'QA',lastName:'AUDIT',phone:'0600000000',email:'qa@example.test'});w.SigmaCRM.openLead(id);const field=d.querySelector('[data-field="notes"]');field.value='Test sauvegarde';field.dispatchEvent(new w.Event('input',{bubbles:true}));field.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(700);console.log('AUTOSAVE',w.SigmaCRM.getLeads().find(l=>l.id===id).notes);
for(const kind of ['courtiers','agents','notaires','ambassadeurs']){w.SigmaContacts.ingest(kind,[{nom:'QA '+kind,email:'test@example.test'}]);w.SigmaCRM.openLead(id);const input=d.querySelector('[data-lead-contact="'+kind+'"][value="QA '+kind+'"]');input.checked=true;input.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(650);}
console.log('CONTACT LINKS', ['brokerName','agentName','notaryBuyer','ambassadorName'].every(k=>w.SigmaCRM.getLeads().find(l=>l.id===id)[k].startsWith('QA')));
for(const route of ['litige','care','pipeline']){w.SigmaCRM.openLead(id);const input=d.querySelector('[data-sav-route][value="'+route+'"]');input.checked=true;input.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(650);console.log('SAV',route,w.SigmaCRM.getLeads().find(l=>l.id===id).litige,w.SigmaCRM.getLeads().find(l=>l.id===id).customCare);}
d.getElementById('closeDrawer').click();w.SigmaCRM.openView('biens');const btn=d.querySelector('[data-edit]');btn.click();console.log('PROPERTY OPENS',!d.getElementById('bienEdit').classList.contains('hidden'));
const rows=[{firstName:'Import',lastName:'QA',email:'import@example.test'}];const a=w.SigmaCRM.ingestFromCloud(rows,'test.csv'),b=w.SigmaCRM.ingestFromCloud(rows,'test.csv');console.log('IMPORT IDEMPOTENT',a.created===1&&b.created===0&&b.updated===1);
w.SigmaCRM.openView('cloud');d.getElementById('sigmaCloudUrl').value='https://example.test/mandat.pdf';d.getElementById('sigmaCloudName').value='Mandat QA';d.getElementById('sigmaCloudAdd').click();await wait(100);console.log('URL DEPOSIT',w.SigmaCloud.getAll().some(x=>x.name==='Mandat QA'));const select=d.querySelector('#sigmaCloudList select[aria-label="Ajouter à un lead"]');select.value=id;select.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(100);const sync=[...d.querySelectorAll('#sigmaCloudList button')].find(b=>b.textContent==='Synchronisation');sync.click();await wait(100);console.log('CLOUD CROSS LINK',w.SigmaCloud.getAll()[0].leadId===id&&!!w.SigmaCloud.getAll()[0].lastSyncAt);w.SigmaCRM.openLead(id);console.log('LEAD DOC LINK',d.getElementById('drawerContent').textContent.includes('Mandat QA'));
const calc=w.SigmaBusiness.calculate,base={stage:'financing',checks:{principle:true},mandatePct:6,business:{netSeller:200000,mandateType:'HT',mode:'A',brokerFees:1200,brokerType:'TTC',brokerRetroRate:10}};console.log('NO EARLY CA',calc(base).sigmaNet===0);console.log('CA COMPROMISE',calc({...base,stage:'compromise'}).sigmaNet===10200);console.log('CA LOAN',calc({...base,stage:'loan'}).sigmaNet===10300);console.log('NO CA FOLLOWUP',calc({...base,stage:'followup'}).sigmaNet===0);
d.getElementById('closeDrawer').click();d.getElementById('bienClose').click();w.SigmaCRM.openView('cloud');d.getElementById('sigmaCloudPasteName').value='leads-audit';d.getElementById('sigmaCloudPasteText').value='Prénom;Nom;Email\nBot;Audit;bot@example.test';d.getElementById('sigmaCloudPasteSave').click();await wait(100);await wait(650);console.log('BOT AUTOMATIC',w.SigmaCRM.getLeads().some(l=>l.firstName==='Bot'&&l.lastName==='Audit'));const push=[...d.querySelectorAll('#sigmaCloudList button')].find(b=>b.textContent==='Tri Bot & Push CRM');push.click();await wait(300);console.log('BOT PUSH',w.SigmaCRM.getLeads().some(l=>l.firstName==='Bot'&&l.lastName==='Audit'));const push2=[...d.querySelectorAll('#sigmaCloudList button')].find(b=>b.textContent==='Tri Bot & Push CRM');push2.click();await wait(300);console.log('BOT NO DUPLICATES',w.SigmaCRM.getLeads().filter(l=>l.firstName==='Bot'&&l.lastName==='Audit').length===1);
const docBefore=w.SigmaCloud.getAll()[0];const archive=[...d.querySelectorAll('#sigmaCloudList button')].find(b=>b.textContent==='Archiver');archive.click();await wait(150);console.log('ARCHIVE PERSISTED',!!w.SigmaCloud.getAll().find(x=>x.createdAt===docBefore.createdAt).archivedAt);const filter=d.getElementById('sigmaArchiveFilter');filter.value='archived';filter.dispatchEvent(new w.Event('change'));console.log('ARCHIVE CONSULTABLE',!!d.querySelector('#sigmaCloudList a'));const restore=[...d.querySelectorAll('#sigmaCloudList button')].find(b=>b.textContent==='Restaurer');restore.click();await wait(150);console.log('ARCHIVE RESTORED',!w.SigmaCloud.getAll().find(x=>x.createdAt===docBefore.createdAt).archivedAt);filter.value='active';filter.dispatchEvent(new w.Event('change'));

w.SigmaCRM.openView('notaires');const form=d.querySelector('[data-contact-form="notaires"]');form.elements.nom.value='Notaire formulaire';form.elements.email.value='notaire@example.test';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));console.log('CONTACT FORM',w.SigmaContacts.getAll('notaires').some(x=>x.nom==='Notaire formulaire'));
w.SigmaCRM.openLead(id);const prop=w.SigmaBiens.getAll()[0];d.getElementById('leadVisitProperty').value=prop.id;d.getElementById('leadVisitReport').value='Visite QA';d.getElementById('leadAddVisit').click();await wait(650);console.log('VISIT SAVED',w.SigmaCRM.getLeads().find(l=>l.id===id).visitedProperties.some(v=>v.id===prop.id&&v.report==='Visite QA'));
console.log('DATES HISTORY',w.SigmaCRM.getLeads().find(l=>l.id===id).timeline.every(t=>!!t.at));await wait(850);console.log('KNOWLEDGE MEMORY',!!w.sigmaPreviewStorage.getItem('sigma.factory.knowledge.v1'));
const pbtn=d.querySelector('[data-open-property]');pbtn.click();console.log('VISIT PROPERTY OPENS',!d.getElementById('bienDetail').classList.contains('hidden'));console.log('PROPERTY LEAD BACKLINK',d.getElementById('bienDetailBody').textContent.includes('QA AUDIT'));
const saved=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));const reload=new JSDOM(fs.readFileSync(source,'utf8'),{url:'https://test.local/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(v){Object.entries(saved).forEach(([k,x])=>v.localStorage.setItem(k,x));v.ResizeObserver=class{observe(){}};v.scrollTo=()=>{};v.matchMedia=()=>({matches:false});v.URL.createObjectURL=()=> 'blob:test';v.URL.revokeObjectURL=()=>{};}});await wait(1300);console.log('RELOAD LEAD',reload.window.SigmaCRM.getLeads().find(l=>l.id===id)?.notes==='Test sauvegarde');console.log('RELOAD CONTACT',reload.window.SigmaContacts.getAll('notaires').some(c=>c.nom==='Notaire formulaire'));reload.window.close();w.SigmaCRM.openView('cloud');d.getElementById('sigmaCloudPasteName').value='Guide fonctionnement SIGMA';d.getElementById('sigmaCloudPasteText').value='Ce guide explique comment fonctionne le service SIGMA Factory. La Datathèque rassemble les sources et le CRM assure le suivi des dossiers. Les informations doivent être vérifiées avant utilisation.';d.getElementById('sigmaCloudPasteSave').click();await wait(1300);w.SigmaCRM.openView('knowledge');console.log('AUTO KNOWLEDGE',JSON.parse(w.sigmaPreviewStorage.getItem('sigma.factory.knowledge.deposits')).length===1&&d.querySelector('#sigmaKnowledgeRows').textContent.includes('Guide fonctionnement SIGMA'));console.log('FINAL ERRORS',errors);dom.window.close();})();
